db.default.driver = com.mysql.cj.jdbc.Driver
db.default.url = "jdbc:mysql://localhost:3306/POS"
db.default.username = root
db.default.password = bs23
# jpa.default = defaultPersistenceUnit
# ebean.default = ['models.*']
# play.evolutions.enabled = true
# play.evolutions.db.default.enabled = true
# play.evolutions.autoApply = true
# jpa.default = "defaultPersistenceUnit"

#jpa.default = defaultPersistenceUnit
#jpa.default = default
#play.modules.enabled += "play.db.jpa.JpaModule"

ebean.default = ["models.*"]
play.evolutions.enabled = false
play.evolutions.autoApply = false